**In this project, I have applied a NaiveBayes Algorithm from Scratch and also make prediction with the help of sklearn library.**

In [2]:
import numpy as np 
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
data = iris.data
target = iris.target

In [6]:
iris_data = np.insert(data, 4, target, axis=1)
iris_data[:4]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ]])

In [7]:
sfi = np.random.permutation(len(iris_data))
iris_data = iris_data[sfi]
iris_data[:5]

array([[6.8, 2.8, 4.8, 1.4, 1. ],
       [5. , 3.3, 1.4, 0.2, 0. ],
       [5.8, 2.6, 4. , 1.2, 1. ],
       [5.6, 2.9, 3.6, 1.3, 1. ],
       [6.2, 3.4, 5.4, 2.3, 2. ]])

In [8]:
train_data = iris_data[26:]
test_data = iris_data[:25]
test_data[:4]

array([[6.8, 2.8, 4.8, 1.4, 1. ],
       [5. , 3.3, 1.4, 0.2, 0. ],
       [5.8, 2.6, 4. , 1.2, 1. ],
       [5.6, 2.9, 3.6, 1.3, 1. ]])

## Bayes theorem

<img src='bayes-theorem.png'>

In [9]:
### STEP-1
## Seperate by classes 
def seperate_by_class(dataset):
    seperate_data = {}
    for i in dataset:
        if i[-1] not in seperate_data:
            seperate_data[i[-1]] = []
        seperate_data[i[-1]].append(i)
    return seperate_data

In [10]:
seperate_by_class(test_data)

{1.0: [array([6.8, 2.8, 4.8, 1.4, 1. ]),
  array([5.8, 2.6, 4. , 1.2, 1. ]),
  array([5.6, 2.9, 3.6, 1.3, 1. ]),
  array([6.4, 2.9, 4.3, 1.3, 1. ]),
  array([6.1, 2.9, 4.7, 1.4, 1. ]),
  array([6. , 2.2, 4. , 1. , 1. ]),
  array([5.4, 3. , 4.5, 1.5, 1. ]),
  array([5.7, 2.9, 4.2, 1.3, 1. ]),
  array([5. , 2. , 3.5, 1. , 1. ]),
  array([7. , 3.2, 4.7, 1.4, 1. ]),
  array([5.7, 2.8, 4.1, 1.3, 1. ])],
 0.0: [array([5. , 3.3, 1.4, 0.2, 0. ]),
  array([4.5, 2.3, 1.3, 0.3, 0. ]),
  array([5. , 3.4, 1.5, 0.2, 0. ]),
  array([5.1, 3.7, 1.5, 0.4, 0. ]),
  array([5. , 3.2, 1.2, 0.2, 0. ]),
  array([5.4, 3.4, 1.7, 0.2, 0. ]),
  array([4.8, 3.4, 1.9, 0.2, 0. ]),
  array([5.8, 4. , 1.2, 0.2, 0. ])],
 2.0: [array([6.2, 3.4, 5.4, 2.3, 2. ]),
  array([6.3, 2.5, 5. , 1.9, 2. ]),
  array([6.7, 3. , 5.2, 2.3, 2. ]),
  array([7.9, 3.8, 6.4, 2. , 2. ]),
  array([7.7, 3. , 6.1, 2.3, 2. ]),
  array([7.7, 2.6, 6.9, 2.3, 2. ])]}

In [11]:
## Find the probability of each class

In [12]:
Sep = seperate_by_class(test_data)
for i in Sep:
    print('The probability for class', i, 'is: %.2f' %(len(Sep[i])/len(test_data)))

The probability for class 1.0 is: 0.44
The probability for class 0.0 is: 0.32
The probability for class 2.0 is: 0.24


In [13]:
def Mean(numbers):
    return sum(numbers)/len(numbers)


In [14]:
def Std_values(numbers):
    mean = Mean(numbers)
    Sum = 0
    for i in numbers:
        Sum += (i-(mean))**2
    stddev = (Sum/len(numbers))**0.5
    return stddev

In [15]:
Std_values(test_data)  ## returns a standard deviation column wise(for each column) and we have 5 columns

array([0.92480484, 0.47993333, 1.73695826, 0.74074557, 0.74404301])

In [16]:
print(test_data.std(axis=0))
test_data.std(axis=1)

[0.92480484 0.47993333 1.73695826 0.74074557 0.74404301]


array([2.17402852, 1.91248529, 1.80044439, 1.67020957, 1.67044904,
       1.62529997, 1.99939991, 1.92083315, 1.78280678, 1.9405154 ,
       1.81614977, 1.92416216, 2.37183473, 1.68689063, 2.26927301,
       2.46981781, 1.96020407, 1.91248529, 1.76793665, 1.54919334,
       2.03725305, 2.2105203 , 1.84564352, 2.28175371, 1.7565876 ])

In [17]:
### STEP-2
### summary coonatins mean, Std and the number of dataset in a specific class
def Find_summary(datasets):
    mean = np.mean(datasets, axis=0)
    std = np.std(datasets, axis=0)
    All_data = []
    for i in zip(mean, std):
        a= list(i)
        a.append(len(datasets))
        All_data.append(a)
    return All_data[:-1]   ## We don't want summary of classes column i.e., 0,1,2

In [18]:
Find_summary(test_data)  ## returns a mean, std for a specific columns in a list format
                        ## We have 4 columns and getting a 4 list of summary except last class column  

[[5.944000000000001, 0.92480484427797, 25],
 [3.008, 0.47993332870306055, 25],
 [3.724000000000001, 1.7369582608686944, 25],
 [1.164, 0.7407455703546258, 25]]

In [19]:
### STEP-3
def Manage_Date_By_Class(dataset):
    Manage = {}
    Sep = seperate_by_class(dataset)
    for i in Sep:
        Manage[i] = Find_summary(Sep[i])
    return Manage

In [20]:
Manage_Date_By_Class(test_data)  ## Returns a class wise summary for each row or dataset

{1.0: [[5.954545454545454, 0.5662695091780886, 11],
  [2.7454545454545456, 0.33673198504458424, 11],
  [4.218181818181819, 0.4152068089697904, 11],
  [1.281818181818182, 0.1526623238522424, 11]],
 0.0: [[5.074999999999999, 0.36314597615834876, 8],
  [3.3374999999999995, 0.4580870550452174, 8],
  [1.4625, 0.22878756522153906, 8],
  [0.2375, 0.06959705453537528, 8]],
 2.0: [[7.083333333333335, 0.7033649282003065, 6],
  [3.0500000000000003, 0.4462809279665294, 6],
  [5.833333333333333, 0.6847546194724713, 6],
  [2.1833333333333336, 0.16749792701868146, 6]]}

## Naiyebayes using gaussian   

<img src='index.png'>

In [21]:
### STEP-4
### we divided above formulae into 2 parts
### first one is lower part and second one is exponential part
def Calculate_probability(x, Mean, Std):
    part_1 = 1 /(Std *((2*np.pi)**0.5))
    part_2 = np.exp((-(x - Mean)**2)/ (2*(Std**2)))
    return part_1 * part_2

In [22]:
Calculate_probability(7.2, 6.4, 0.4)  ## for 2.0: [[6.3625, 0.41814321709194346, 25] 

0.1349774162829703

In [23]:
### STEP-5  ---> Last step
### Apply a naive bayes formulae
def Find_Probability(datasets, TestData):
    total_rows = 0    ## first we find the number of rows
    for i in datasets:
        total_rows += datasets[i][0][-1]  ## it is taking the no. of dataset in each class. As we calculate in summary
                                          ## we know in our case total rows are 25
    prob = {}
    for i in datasets:
        prob[i] = datasets[i][0][-1]/total_rows  ## return prob for each class {2.0: 0.32, 1.0: 0.28, 0.0: 0.4}
                                                 ## This is our P(O) i.e., prob for each outcomes
        class_summary = datasets[i]
        for j in range(len(class_summary)):
            mean, std, num = class_summary[j]   ## Bcz it has mean, std and no. of dataset in class
            x = TestData[j]
            Newprob = Calculate_probability(x, mean, std)
            prob[i] = prob[i] * Newprob         ## Bcz in our NB formulae we multiply P(each events,En) with P(each class or outcm)  
    return prob

In [24]:
summary = Manage_Date_By_Class(test_data)
summary

{1.0: [[5.954545454545454, 0.5662695091780886, 11],
  [2.7454545454545456, 0.33673198504458424, 11],
  [4.218181818181819, 0.4152068089697904, 11],
  [1.281818181818182, 0.1526623238522424, 11]],
 0.0: [[5.074999999999999, 0.36314597615834876, 8],
  [3.3374999999999995, 0.4580870550452174, 8],
  [1.4625, 0.22878756522153906, 8],
  [0.2375, 0.06959705453537528, 8]],
 2.0: [[7.083333333333335, 0.7033649282003065, 6],
  [3.0500000000000003, 0.4462809279665294, 6],
  [5.833333333333333, 0.6847546194724713, 6],
  [2.1833333333333336, 0.16749792701868146, 6]]}

In [25]:
out = Find_Probability(summary, test_data[21])  ## returns the probabilty that data set belongs to that class
out

{1.0: 0.02549300805484946,
 0.0: 1.987953432469493e-110,
 2.0: 7.174797642254352e-07}

In [26]:
Class = []
Prob = []
for i in out:
    Class.append(int(i))
    Prob.append(float(out[i]))
pred = Class[Prob.index(max(Prob))]  ## returns the class have max probability
pred

1

In [27]:
test_data[1]

array([5. , 3.3, 1.4, 0.2, 0. ])

Our model did a correct prediction. By this we can predict the class for single dataset.

### Let's try to make prediction for all the test data.

In [28]:
def prediction(traindata, testdata):
    Summary = Manage_Date_By_Class(traindata)
    Allpred = []
    
    for data in testdata:
        out = Find_Probability(Summary, data)
        Class = []
        Prob = []
        for i in out:
            Class.append(int(i))
            Prob.append(float(out[i]))
        ypred = Class[np.argmax(Prob)]
        Allpred.append(ypred)
    return Allpred

In [29]:
prediction(train_data, test_data) 

[1, 0, 1, 1, 2, 0, 1, 0, 2, 1, 2, 1, 2, 1, 2, 2, 0, 0, 1, 1, 0, 1, 0, 0, 1]

In [30]:
actual = test_data[:,-1]
actual

array([1., 0., 1., 1., 2., 0., 1., 0., 2., 1., 2., 1., 2., 1., 2., 2., 0.,
       0., 1., 1., 0., 1., 0., 0., 1.])

### Using sklearn

In [31]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

In [32]:
model = model.fit(train_data[:,:-1], train_data[:,-1])

In [33]:
predicted = model.predict(test_data[:,:-1])

In [34]:
predicted

array([1., 0., 1., 1., 2., 0., 1., 0., 2., 1., 2., 1., 2., 1., 2., 2., 0.,
       0., 1., 1., 0., 1., 0., 0., 1.])

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix

score = accuracy_score(actual, predicted)
score

1.0

In [36]:
confusion_matrix(actual, predicted)

array([[ 8,  0,  0],
       [ 0, 11,  0],
       [ 0,  0,  6]], dtype=int64)

Our model have a good accuracy score